travis:
  secure:
    BINSTAR_TOKEN: FwE6prqupNWo7qyW+dlFn+WG7QAAWyK5aCD+FdYu+qJ+G0Z3tEZfeo/PCTsiiGycSK8NNNuiSagHKLrNXiR0fq6p2S1/c+hXQVObr7fN+vpjq8LS7KWg++CQLl1gGtCFmGYZuTGahUPGLmfTexsFPhND/3JC3c1NtYS58vO11xdQw6lcsdsCrJm93v7udBLA5NUYzO6vXxohffClTcxu7dSgeP8DwGn7oeRIvCP8p3JKXLl9dy2aIEUTvtBkmMF3IsO+h7SxlaOtrbASjr/Vle1dWJy1KCUtMQAxtYFp+VemhWugrCSEW5lQwCF7o/5JESvzsjqVso5LHTdvdbvAQtgEgKG+tFZIyFI3d3eShlEtCB34B1Bt4ubaAfWhDNtx4qa/77K2+9cjJeBc7NSomOIY/1Iz6OZ1pDRvDSRRTQy70B5/34QqIOwchfn2dFWlnIZF7xbg95xCfE4jvcdF/uLxMvHbRD4XXNG+0obUaXEGRqIKgjJV4dK/dc0gxRZhDXRabLxfl6BimZXL4CFF8QOdA1Kqfh8q6x/2qHDfvkBoVKjgWpAJQtvJZkog4QAlJ+nswRWjWlKCEiAnUhB8KpYMHrEe36AC/VRUWosLsSw44XyBxeMKq4YGKPQfCRXqgIFLwIfeVHNVkgTDfgP8rvGKhS7I4TiTRiH+eLehZGs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
