travis:
  secure:
    BINSTAR_TOKEN: b/bSYTNUFQDIqvUlnDoHrwXmPElJpmxRk0wN1Bn+B3swVdoZMj91Jzao3rGzucJTIFoxGkMRnPNQCmZ8OfJTgtfIVDIRajzqzoR+wRmXlNhcpasbR1BDMVfA5tZXW8nP6KDc20h4AxMod08zEvsWrUwOAHlE9wW5aphckrRtWQEplCLO4Z+hgHM9z6oKQSsGmExIu7ihVvNUXk6n376KjluowKa9QkL9bBAakQGpRXLEJYsSEb/8ZV5k8P+/VsNF7jm/7hSn/Aejfu96LHQJCvL5qstmXSGfs23VUvrWdHJZLE19+Fdx815nNckKAXCu1AzpwStxNnEH0TV5RmKA/QAQ9psGzeGc4y3hMixsVF5z1tWgIM9d5mljzIurNy7iLa/nRnAw/l5NrHtQM/QE5qKNAU4EG3vkr2RmiVDLaP85as4fxUENTdjo/Ei6H4qTVxoLin0Y3kv1aIme+iFgOrNG1dQ22j4EhpnVyv6umOOF+Sdz/itzeNcoRUJ/c2UiXhCcaPe5n1KNCXv8tfXntm2Oh44Afqanryrgeb57CDSG9254EjGS3ZSTtk8tswa3Oco7E0IEIG8ZNQ4UyD+qyGnBW+vR5NyiM5VCBlCZE8eoSTMOpwaDkun84AvFd0bGHAxkR2nN05xk50NLaUOUAn/ix6pe9fHORirF78wrQqc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
